controller_manager:
  ros__parameters:
    update_rate: 30

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
    gains:
      shoulder_pan_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
      shoulder_lift_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
      elbow_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
      wrist_1_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
      wrist_2_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
      wrist_3_joint: {p: 200.0, d: 0.1, i: 0.01, i_clamp: 1.0}
    position_limits:
      shoulder_pan_joint: {min: -6.2832, max: 6.2832}
      shoulder_lift_joint: {min: -6.2832, max: 6.2832}
      elbow_joint: {min: -3.1416, max: 3.1416}
      wrist_1_joint: {min: -6.2832, max: 6.2832}
      wrist_2_joint: {min: -6.2832, max: 6.2832}
      wrist_3_joint: {min: -6.2832, max: 6.2832}
    velocity_limits:
      shoulder_pan_joint: 3.1416
      shoulder_lift_joint: 3.1416
      elbow_joint: 3.1416
      wrist_1_joint: 3.1416
      wrist_2_joint: 3.1416
      wrist_3_joint: 3.1416
    effort_limits:
      shoulder_pan_joint: 150
      shoulder_lift_joint: 150
      elbow_joint: 150
      wrist_1_joint: 28
      wrist_2_joint: 28
      wrist_3_joint: 28
